# Generated by Django 3.1 on 2022-04-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_Do_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(blank=True, max_length=250)),
                ('titel', models.CharField(blank=True, max_length=100)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
