# Generated by Django 3.1 on 2022-04-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_list',
            name='list_id',
        ),
    ]
