# Generated by Django 3.1 on 2022-04-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createlist', '0002_remove_to_do_list_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='list_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
