# Generated by Django 3.1 on 2022-04-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createlist', '0003_to_do_list_list_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='to_do_list',
            options={'ordering': ['date_add']},
        ),
    ]
